### ISSUE TITLE
Reduce motion

### ISSUE THREAD

**Issue by zouloux** [solid-js/css-flat#2]
Désactivation de toutes les animations CSS (tant pis pour le JS) comme comportement par défaut lorsque l'utilisateur a sélectionné l'option "reduce motion" sur MacOS ou iOS

https://twitter.com/scottjehl/status/1085600505299111936

**Comment by zouloux** [comment]
```css
@media (prefers-reduced-motion: reduce) {
  * {
    animation: none !important;
    transition: none !important;
  }
}
```
T'es penses quoi ?
